[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ba_openai"
version = "0.0.33"
dependencies = [
    "requests>=2.32.2",
    "tqdm>=4.67.1",
    "openai>=1.66.2",
    "numpy>=1.26.1",
    "httpx>=0.28.1",
    "pillow>=10.2.0"
]
authors = [
  { name="Daniel Guetta", email="daniel@guetta.com" },
]
description = "A version of the OpenAI package that allows the caching of responses, tailored for the CBS BA class."
readme = "readme.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/danguetta/cached_openai"
Issues = "https://github.com/danguetta/cached_openai/issues"